app = 'benbot-discord'
primary_region = 'iad'

[build]

[processes]
  bot = 'node index.js'

[mounts]
  source = 'benbot_data'
  destination = '/data'
  processes = ['bot']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 256
  processes = ['bot']
